# Generated by Django 5.2.4 on 2025-08-12 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_rename_manufacture_manufacturer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='manufacture',
            new_name='manufacturer',
        ),
    ]
